### ISSUE TITLE
How does a cookie httpOnly work with AJAX requests?

### ISSUE THREAD

**Issue by stlsmiths** [ilich/node-2fa#1]
Hi Ilya, I was a 2016 JS Summit attendee but couldn't participate live for your session due to scheduling.

I use Passport Localstrategy in my apps and was wondering how the cookie setup as httpOnly 
     https://github.com/ilich/node-2fa/blob/master/app/routes/index.js#L43
works when you have a node server that serves both (a) html content and (b) AJAX request data ... i.e. thru RESTful api requests?

If you setup the authentication cookie as httpOnly don't the ajax requests get rejected ?

Didn't know how to communicate to you ... hope thru this issue is okay.

Todd

**Comment by ilich** [comment]
Hello Todd,

You HTTP only cookies will be passed to all of your AJAX requests. HTTP only cookies are normal cookies, but they are not accessible through document.cookie object from JavaScript.

Your AJAX requests won't be rejected.

You can contact me on Twitter: @ilich_x86. Send me a private message if you need more information or we can continue the discussion on GitHub as well.

Sincerely,
Ilya
